from typing import TypedDict


class DailyQuestion(TypedDict):
    prompt: str
    options: list[str]
    correct_option_index: int
    explanation: str


DAILY_GLUCOSE_REWARD = 25


DAILY_QUESTIONS: list[DailyQuestion] = [
    {
        "prompt": "What is the atomic number of oxygen?",
        "options": ["6", "7", "8", "9"],
        "correct_option_index": 2,
        "explanation": "Atomic number equals the number of protons. Oxygen has 8 protons.",
    },
    {
        "prompt": "Which particle has a negative charge?",
        "options": ["Proton", "Neutron", "Electron", "Nucleus"],
        "correct_option_index": 2,
        "explanation": "Electrons carry a negative charge, protons are positive, and neutrons are neutral.",
    },
    {
        "prompt": "What is the chemical symbol for sodium?",
        "options": ["S", "So", "Na", "Sd"],
        "correct_option_index": 2,
        "explanation": "Sodium uses the symbol Na from its Latin name, natrium.",
    },
    {
        "prompt": "How many valence electrons does chlorine have?",
        "options": ["5", "6", "7", "8"],
        "correct_option_index": 2,
        "explanation": "Chlorine is in Group 17, so it has 7 valence electrons.",
    },
    {
        "prompt": "Which bond forms when electrons are shared between atoms?",
        "options": ["Ionic bond", "Covalent bond", "Metallic bond", "Hydrogen bond"],
        "correct_option_index": 1,
        "explanation": "Covalent bonds form when atoms share pairs of electrons.",
    },
    {
        "prompt": "What is the formula for water?",
        "options": ["HO", "H2O", "H2O2", "OH2"],
        "correct_option_index": 1,
        "explanation": "Water contains two hydrogen atoms and one oxygen atom: H2O.",
    },
    {
        "prompt": "Which state of matter has a definite volume but no definite shape?",
        "options": ["Solid", "Liquid", "Gas", "Plasma"],
        "correct_option_index": 1,
        "explanation": "Liquids keep a definite volume but take the shape of their container.",
    },
    {
        "prompt": "What is the pH of a neutral solution at 25 degrees Celsius?",
        "options": ["0", "5", "7", "14"],
        "correct_option_index": 2,
        "explanation": "Pure water at 25 degrees Celsius is neutral and has a pH of 7.",
    },
    {
        "prompt": "Which gas law states that pressure and volume are inversely related at constant temperature?",
        "options": ["Charles's law", "Avogadro's law", "Boyle's law", "Gay-Lussac's law"],
        "correct_option_index": 2,
        "explanation": "Boyle's law says pressure increases as volume decreases when temperature stays constant.",
    },
    {
        "prompt": "How many grams are in 1 mole of carbon-12?",
        "options": ["6 grams", "12 grams", "24 grams", "1 gram"],
        "correct_option_index": 1,
        "explanation": "One mole of carbon-12 has a mass of exactly 12 grams.",
    },
    {
        "prompt": "Which subatomic particle determines the identity of an element?",
        "options": ["Electron", "Neutron", "Proton", "Photon"],
        "correct_option_index": 2,
        "explanation": "The number of protons defines the element.",
    },
    {
        "prompt": "What is the formula for table salt?",
        "options": ["NaCl", "KCl", "Na2Cl", "ClNa2"],
        "correct_option_index": 0,
        "explanation": "Table salt is sodium chloride, written as NaCl.",
    },
    {
        "prompt": "Which of these is a noble gas?",
        "options": ["Nitrogen", "Oxygen", "Neon", "Chlorine"],
        "correct_option_index": 2,
        "explanation": "Neon is a noble gas in Group 18.",
    },
    {
        "prompt": "When an atom loses an electron, it becomes a:",
        "options": ["Anion", "Cation", "Isotope", "Molecule"],
        "correct_option_index": 1,
        "explanation": "Losing electrons leaves a net positive charge, making the atom a cation.",
    },
    {
        "prompt": "Which quantity is conserved in a balanced chemical equation?",
        "options": ["Color", "Temperature", "Mass", "Volume"],
        "correct_option_index": 2,
        "explanation": "Balanced equations obey the law of conservation of mass.",
    },
    {
        "prompt": "What is the molar mass of O2?",
        "options": ["16 g/mol", "18 g/mol", "32 g/mol", "64 g/mol"],
        "correct_option_index": 2,
        "explanation": "Each oxygen atom is about 16 g/mol, so O2 is about 32 g/mol.",
    },
    {
        "prompt": "Which type of reaction combines simpler substances into a more complex substance?",
        "options": ["Decomposition", "Synthesis", "Single replacement", "Combustion"],
        "correct_option_index": 1,
        "explanation": "A synthesis reaction combines reactants into one main product.",
    },
    {
        "prompt": "Which intermolecular force is strongest among these choices?",
        "options": ["London dispersion forces", "Dipole-dipole forces", "Hydrogen bonding", "None are intermolecular forces"],
        "correct_option_index": 2,
        "explanation": "Hydrogen bonding is a particularly strong dipole-dipole interaction.",
    },
    {
        "prompt": "What is the oxidation number of oxygen in most compounds?",
        "options": ["+2", "+1", "-1", "-2"],
        "correct_option_index": 3,
        "explanation": "Oxygen usually has an oxidation number of -2, except in special cases like peroxides.",
    },
    {
        "prompt": "Which lab instrument is typically used to measure liquid volume accurately?",
        "options": ["Thermometer", "Graduated cylinder", "Balance", "Evaporating dish"],
        "correct_option_index": 1,
        "explanation": "A graduated cylinder is designed to measure liquid volume accurately.",
    },
    {
        "prompt": "If a solution has a high concentration of H+ ions, it is:",
        "options": ["Basic", "Neutral", "Acidic", "Saturated"],
        "correct_option_index": 2,
        "explanation": "A high hydrogen ion concentration corresponds to an acidic solution.",
    },
    {
        "prompt": "Which of these is an example of a physical change?",
        "options": ["Rusting iron", "Burning methane", "Melting ice", "Digesting food"],
        "correct_option_index": 2,
        "explanation": "Melting changes the state of water without changing its chemical identity.",
    },
    {
        "prompt": "What is the coefficient of O2 when balancing 2H2 + O2 -> 2H2O?",
        "options": ["1", "2", "3", "4"],
        "correct_option_index": 0,
        "explanation": "The balanced equation is 2H2 + O2 -> 2H2O, so the coefficient is 1.",
    },
    {
        "prompt": "Which element is more electronegative?",
        "options": ["Sodium", "Fluorine", "Calcium", "Aluminum"],
        "correct_option_index": 1,
        "explanation": "Fluorine is the most electronegative element on the periodic table.",
    },
    {
        "prompt": "What happens to gas volume when temperature increases at constant pressure?",
        "options": ["It decreases", "It stays the same", "It increases", "It becomes zero"],
        "correct_option_index": 2,
        "explanation": "Charles's law says gas volume increases with temperature at constant pressure.",
    },
    {
        "prompt": "Which formula represents calcium chloride?",
        "options": ["CaCl", "CaCl2", "Ca2Cl", "Ca2Cl2"],
        "correct_option_index": 1,
        "explanation": "Calcium forms a 2+ ion and chloride forms a 1- ion, so the formula is CaCl2.",
    },
    {
        "prompt": "What is the empirical formula of hydrogen peroxide, H2O2?",
        "options": ["HO", "H2O2", "H2O", "O2H2"],
        "correct_option_index": 0,
        "explanation": "The simplest whole-number ratio in H2O2 is 1:1, so the empirical formula is HO.",
    },
    {
        "prompt": "Which periodic trend generally increases from left to right across a period?",
        "options": ["Atomic radius", "Metallic character", "Electronegativity", "Shielding effect"],
        "correct_option_index": 2,
        "explanation": "Electronegativity generally increases across a period from left to right.",
    },
    {
        "prompt": "A catalyst in a chemical reaction does what?",
        "options": ["Raises activation energy", "Gets used up permanently", "Speeds up the reaction", "Changes the products formed"],
        "correct_option_index": 2,
        "explanation": "A catalyst speeds a reaction by lowering activation energy and is not consumed overall.",
    },
    {
        "prompt": "What is the concentration of a solution with 2 moles of solute in 1 liter of solution?",
        "options": ["0.5 M", "1 M", "2 M", "3 M"],
        "correct_option_index": 2,
        "explanation": "Molarity is moles per liter, so 2 moles in 1 liter is 2 M.",
    },
    {
        "prompt": "Which element has the chemical symbol Fe?",
        "options": ["Fluorine", "Francium", "Iron", "Fermium"],
        "correct_option_index": 2,
        "explanation": "Fe is the symbol for iron, from the Latin word ferrum.",
    },
    {
        "prompt": "What type of bond forms between a metal and a nonmetal?",
        "options": ["Ionic bond", "Covalent bond", "Hydrogen bond", "Network bond"],
        "correct_option_index": 0,
        "explanation": "A metal and a nonmetal typically form an ionic bond by electron transfer.",
    },
    {
        "prompt": "How many neutrons does carbon-14 have?",
        "options": ["6", "8", "14", "20"],
        "correct_option_index": 1,
        "explanation": "Carbon has 6 protons, so carbon-14 has 14 minus 6, or 8 neutrons.",
    },
    {
        "prompt": "Which gas is produced when an acid reacts with a carbonate?",
        "options": ["Oxygen", "Hydrogen", "Carbon dioxide", "Nitrogen"],
        "correct_option_index": 2,
        "explanation": "Acid-carbonate reactions produce a salt, water, and carbon dioxide gas.",
    },
    {
        "prompt": "What is the name of the process where a solid changes directly into a gas?",
        "options": ["Condensation", "Sublimation", "Deposition", "Evaporation"],
        "correct_option_index": 1,
        "explanation": "Sublimation is the phase change from solid directly to gas.",
    },
    {
        "prompt": "Which of these substances is most likely to conduct electricity in aqueous solution?",
        "options": ["Sugar", "Sodium chloride", "Carbon dioxide", "Ethanol"],
        "correct_option_index": 1,
        "explanation": "Sodium chloride dissociates into ions in water, so it conducts electricity well.",
    },
    {
        "prompt": "What is the oxidation number of sodium in NaCl?",
        "options": ["-1", "0", "+1", "+2"],
        "correct_option_index": 2,
        "explanation": "Sodium usually forms a +1 ion in ionic compounds like NaCl.",
    },
    {
        "prompt": "Which quantity is measured in joules?",
        "options": ["Pressure", "Energy", "Molarity", "Density"],
        "correct_option_index": 1,
        "explanation": "The joule is the SI unit of energy.",
    },
    {
        "prompt": "What is the formula of the sulfate ion?",
        "options": ["SO3 2-", "SO4 2-", "S2O4 2-", "SO4 -"],
        "correct_option_index": 1,
        "explanation": "The sulfate ion is SO4 with a 2- charge.",
    },
    {
        "prompt": "Which type of reaction involves a hydrocarbon reacting with oxygen to produce carbon dioxide and water?",
        "options": ["Synthesis", "Combustion", "Neutralization", "Precipitation"],
        "correct_option_index": 1,
        "explanation": "That pattern describes a combustion reaction.",
    },
    {
        "prompt": "What is the approximate pH range of a basic solution?",
        "options": ["Less than 7", "Equal to 7", "Greater than 7", "Always exactly 14"],
        "correct_option_index": 2,
        "explanation": "Basic solutions have a pH above 7.",
    },
    {
        "prompt": "Which element is located in Period 3, Group 1 of the periodic table?",
        "options": ["Lithium", "Sodium", "Potassium", "Magnesium"],
        "correct_option_index": 1,
        "explanation": "Sodium is in Period 3 and Group 1.",
    },
    {
        "prompt": "What does a pH indicator do?",
        "options": ["Measures mass", "Changes color based on acidity", "Raises temperature", "Increases concentration"],
        "correct_option_index": 1,
        "explanation": "A pH indicator changes color depending on the acidity or basicity of a solution.",
    },
    {
        "prompt": "Which particle is found in the nucleus of every atom except ordinary hydrogen?",
        "options": ["Electron", "Neutron", "Photon", "Positron"],
        "correct_option_index": 1,
        "explanation": "Most atomic nuclei contain neutrons, but ordinary hydrogen-1 does not.",
    },
    {
        "prompt": "What is the formula for ammonia?",
        "options": ["NH3", "NH4", "N2H3", "NO3"],
        "correct_option_index": 0,
        "explanation": "Ammonia is NH3, one nitrogen atom bonded to three hydrogen atoms.",
    },
    {
        "prompt": "Which property generally decreases down Group 17?",
        "options": ["Atomic radius", "Number of energy levels", "Electronegativity", "Mass number"],
        "correct_option_index": 2,
        "explanation": "Electronegativity generally decreases as you move down a group.",
    },
    {
        "prompt": "How many significant figures are in 0.04050?",
        "options": ["3", "4", "5", "6"],
        "correct_option_index": 1,
        "explanation": "The significant figures are 4, 0, 5, and the trailing 0, so there are 4 total.",
    },
    {
        "prompt": "Which of these is a strong acid commonly taught in introductory chemistry?",
        "options": ["Acetic acid", "Hydrochloric acid", "Carbonic acid", "Phosphoric acid"],
        "correct_option_index": 1,
        "explanation": "Hydrochloric acid, HCl, is one of the classic strong acids.",
    },
    {
        "prompt": "What is the name of the horizontal rows on the periodic table?",
        "options": ["Groups", "Families", "Periods", "Series"],
        "correct_option_index": 2,
        "explanation": "The horizontal rows on the periodic table are called periods.",
    },
    {
        "prompt": "What is produced at the cathode during the electrolysis of molten sodium chloride?",
        "options": ["Chlorine gas", "Sodium metal", "Oxygen gas", "Hydrogen gas"],
        "correct_option_index": 1,
        "explanation": "At the cathode, sodium ions gain electrons and form sodium metal.",
    },
    {
        "prompt": "Which element has the highest electronegativity on the periodic table?",
        "options": ["Oxygen", "Chlorine", "Nitrogen", "Fluorine"],
        "correct_option_index": 3,
        "explanation": "Fluorine is the most electronegative element.",
    },
    {
        "prompt": "What is the charge on an oxide ion?",
        "options": ["1-", "2-", "1+", "2+"],
        "correct_option_index": 1,
        "explanation": "Oxygen usually gains two electrons to form O2-.",
    },
    {
        "prompt": "Which formula is the nitrate ion?",
        "options": ["NO2 -", "NO3 -", "N2O3", "NO4 -"],
        "correct_option_index": 1,
        "explanation": "The nitrate ion has the formula NO3 with a 1- charge.",
    },
    {
        "prompt": "How many molecules are represented by the coefficient 3 in 3CO2?",
        "options": ["1 molecule", "2 molecules", "3 molecules", "6 molecules"],
        "correct_option_index": 2,
        "explanation": "A coefficient tells how many units are present, so 3CO2 means 3 molecules of carbon dioxide.",
    },
    {
        "prompt": "Which element is an alkali metal?",
        "options": ["Calcium", "Potassium", "Aluminum", "Argon"],
        "correct_option_index": 1,
        "explanation": "Potassium is in Group 1, the alkali metals.",
    },
    {
        "prompt": "Which quantity is typically measured with a balance?",
        "options": ["Volume", "Mass", "Temperature", "Pressure"],
        "correct_option_index": 1,
        "explanation": "A balance is used to measure mass.",
    },
    {
        "prompt": "What is the name of HCl when dissolved in water?",
        "options": ["Hydrogen chloride", "Hydrochloric acid", "Chloric acid", "Hypochlorous acid"],
        "correct_option_index": 1,
        "explanation": "HCl in aqueous solution is called hydrochloric acid.",
    },
    {
        "prompt": "Which process occurs when a gas turns directly into a solid?",
        "options": ["Sublimation", "Deposition", "Melting", "Vaporization"],
        "correct_option_index": 1,
        "explanation": "Deposition is the direct phase change from gas to solid.",
    },
    {
        "prompt": "How many atoms are in one molecule of methane, CH4?",
        "options": ["4", "5", "6", "8"],
        "correct_option_index": 1,
        "explanation": "CH4 contains 1 carbon atom and 4 hydrogen atoms for a total of 5 atoms.",
    },
    {
        "prompt": "What kind of substance is a proton donor according to Bronsted-Lowry theory?",
        "options": ["Acid", "Base", "Salt", "Catalyst"],
        "correct_option_index": 0,
        "explanation": "A Bronsted-Lowry acid donates a proton.",
    },
    {
        "prompt": "Which of these elements is a halogen?",
        "options": ["Bromine", "Boron", "Barium", "Beryllium"],
        "correct_option_index": 0,
        "explanation": "Bromine is in Group 17, the halogens.",
    },
    {
        "prompt": "If 4.0 grams of NaOH are dissolved to make 1.0 liter of solution, what is the molarity? (NaOH molar mass about 40 g/mol)",
        "options": ["0.01 M", "0.1 M", "1.0 M", "10.0 M"],
        "correct_option_index": 1,
        "explanation": "4.0 g divided by 40 g/mol is 0.1 mol, so the solution is 0.1 M.",
    },
    {
        "prompt": "Which trend generally increases down a group?",
        "options": ["Ionization energy", "Electronegativity", "Atomic radius", "Nonmetallic character"],
        "correct_option_index": 2,
        "explanation": "Atomic radius generally increases down a group because atoms gain energy levels.",
    },
    {
        "prompt": "What is the correct name for CO2?",
        "options": ["Carbon monoxide", "Carbon dioxide", "Cobalt dioxide", "Carbon oxide"],
        "correct_option_index": 1,
        "explanation": "CO2 is named carbon dioxide because it contains two oxygen atoms.",
    },
    {
        "prompt": "What is the primary unit for temperature in most chemistry labs in the United States classroom setting?",
        "options": ["Kelvin", "Fahrenheit", "Celsius", "Rankine"],
        "correct_option_index": 2,
        "explanation": "Celsius is the temperature scale most often used in classroom chemistry labs.",
    },
    {
        "prompt": "Which statement about isotopes is true?",
        "options": ["They have different numbers of protons", "They have different numbers of neutrons", "They have different numbers of valence electrons in neutral atoms", "They are always ions"],
        "correct_option_index": 1,
        "explanation": "Isotopes are atoms of the same element with different numbers of neutrons.",
    },
    {
        "prompt": "What is the formula for magnesium oxide?",
        "options": ["MgO", "Mg2O", "MgO2", "Mg2O2"],
        "correct_option_index": 0,
        "explanation": "Magnesium forms Mg2+ and oxide forms O2-, so the formula is MgO.",
    },
    {
        "prompt": "Which type of mixture has a uniform composition throughout?",
        "options": ["Heterogeneous mixture", "Homogeneous mixture", "Suspension", "Colloid only"],
        "correct_option_index": 1,
        "explanation": "A homogeneous mixture has a uniform composition throughout.",
    },
    {
        "prompt": "Which gas is most abundant in Earth's atmosphere?",
        "options": ["Oxygen", "Carbon dioxide", "Nitrogen", "Argon"],
        "correct_option_index": 2,
        "explanation": "Nitrogen makes up most of Earth's atmosphere.",
    },
    {
        "prompt": "What is the name of the energy required to start a chemical reaction?",
        "options": ["Kinetic energy", "Potential energy", "Activation energy", "Thermal energy"],
        "correct_option_index": 2,
        "explanation": "Activation energy is the minimum energy needed to start a reaction.",
    },
    {
        "prompt": "Which equation shows a neutralization reaction?",
        "options": ["Acid + base -> salt + water", "Metal + oxygen -> oxide", "Hydrocarbon + oxygen -> carbon dioxide + water", "Salt -> metal + nonmetal"],
        "correct_option_index": 0,
        "explanation": "Neutralization is the reaction of an acid and a base to form salt and water.",
    },
    {
        "prompt": "Which element has 17 protons?",
        "options": ["Argon", "Chlorine", "Sulfur", "Potassium"],
        "correct_option_index": 1,
        "explanation": "An atom with 17 protons is chlorine.",
    },
    {
        "prompt": "What is the formula for phosphoric acid?",
        "options": ["H3PO4", "H2PO4", "HPO4", "H3PO3"],
        "correct_option_index": 0,
        "explanation": "Phosphoric acid has the formula H3PO4.",
    },
    {
        "prompt": "Which variable is held constant in Gay-Lussac's law?",
        "options": ["Pressure", "Volume", "Temperature", "Number of moles only"],
        "correct_option_index": 1,
        "explanation": "Gay-Lussac's law relates pressure and temperature at constant volume.",
    },
    {
        "prompt": "What is the SI unit for amount of substance?",
        "options": ["Gram", "Mole", "Liter", "Pascal"],
        "correct_option_index": 1,
        "explanation": "The mole is the SI unit for amount of substance.",
    },
    {
        "prompt": "Which type of solid is made of positive ions in a sea of delocalized electrons?",
        "options": ["Ionic solid", "Molecular solid", "Metallic solid", "Covalent network solid"],
        "correct_option_index": 2,
        "explanation": "Metallic solids are held together by metallic bonding with delocalized electrons.",
    },
    {
        "prompt": "What is the oxidation number of hydrogen in most compounds?",
        "options": ["-2", "-1", "+1", "+2"],
        "correct_option_index": 2,
        "explanation": "Hydrogen usually has an oxidation number of +1 in compounds.",
    },
    {
        "prompt": "Which type of radiation has no mass and no charge?",
        "options": ["Alpha", "Beta", "Gamma", "Proton"],
        "correct_option_index": 2,
        "explanation": "Gamma radiation is electromagnetic energy with no mass and no charge.",
    },
    {
        "prompt": "What is the molar mass of CO2?",
        "options": ["28 g/mol", "32 g/mol", "44 g/mol", "46 g/mol"],
        "correct_option_index": 2,
        "explanation": "Carbon dioxide is 12 + 16 + 16, so its molar mass is 44 g/mol.",
    },
    {
        "prompt": "Which property best distinguishes a chemical change from a physical change?",
        "options": ["A new substance forms", "The sample changes shape", "The sample changes size", "The sample changes location"],
        "correct_option_index": 0,
        "explanation": "A chemical change forms one or more new substances.",
    },
    {
        "prompt": "What is the formula for aluminum oxide?",
        "options": ["AlO", "Al2O", "AlO3", "Al2O3"],
        "correct_option_index": 3,
        "explanation": "Aluminum forms Al3+ and oxide is O2-, so the balanced formula is Al2O3.",
    },
    {
        "prompt": "Which law says equal volumes of gases at the same temperature and pressure contain equal numbers of particles?",
        "options": ["Boyle's law", "Charles's law", "Avogadro's law", "Dalton's law"],
        "correct_option_index": 2,
        "explanation": "Avogadro's law relates gas volume to the number of particles at fixed temperature and pressure.",
    },
    {
        "prompt": "Which periodic-table region contains the transition metals?",
        "options": ["s-block", "p-block", "d-block", "f-block only"],
        "correct_option_index": 2,
        "explanation": "The transition metals occupy the d-block of the periodic table.",
    },
    {
        "prompt": "What is the empirical formula for C6H12O6?",
        "options": ["CH2O", "C2H4O2", "C3H6O3", "CHO"],
        "correct_option_index": 0,
        "explanation": "Divide each subscript by 6 to get the simplest ratio: CH2O.",
    },
    {
        "prompt": "Which type of reaction occurs when one element replaces another in a compound?",
        "options": ["Synthesis", "Single replacement", "Double replacement", "Decomposition"],
        "correct_option_index": 1,
        "explanation": "A single-replacement reaction occurs when one element displaces another from a compound.",
    },
    {
        "prompt": "What is the common name for aqueous NH3?",
        "options": ["Ammonia", "Ammonium", "Nitric acid", "Hydrazine"],
        "correct_option_index": 0,
        "explanation": "NH3 is ammonia; in water it acts as a weak base.",
    },
    {
        "prompt": "Which is the correct electron configuration ending for a Group 18 noble gas other than helium?",
        "options": ["ns1", "ns2 np1", "ns2 np6", "ns2 np4"],
        "correct_option_index": 2,
        "explanation": "Noble gases other than helium have full valence shells ending in ns2 np6.",
    },
    {
        "prompt": "What is the name of the compound CaCO3?",
        "options": ["Calcium chlorate", "Calcium carbonate", "Calcium carbide", "Calcium cyanide"],
        "correct_option_index": 1,
        "explanation": "CaCO3 is calcium carbonate.",
    },
    {
        "prompt": "Which of these is a product of cellular respiration and combustion?",
        "options": ["Hydrogen gas", "Carbon dioxide", "Ammonia", "Chlorine gas"],
        "correct_option_index": 1,
        "explanation": "Carbon dioxide is a common product of both cellular respiration and combustion.",
    },
    {
        "prompt": "What happens to the concentration of a solution when more solvent is added without adding solute?",
        "options": ["It increases", "It decreases", "It stays the same", "It becomes zero immediately"],
        "correct_option_index": 1,
        "explanation": "Adding solvent dilutes the solution, so concentration decreases.",
    },
    {
        "prompt": "Which formula represents sulfuric acid?",
        "options": ["H2SO3", "H2SO4", "HSO4", "H2S"],
        "correct_option_index": 1,
        "explanation": "Sulfuric acid has the formula H2SO4.",
    },
    {
        "prompt": "Which particle has nearly the same mass as a proton but no charge?",
        "options": ["Electron", "Neutron", "Positron", "Photon"],
        "correct_option_index": 1,
        "explanation": "Neutrons are neutral and have nearly the same mass as protons.",
    },
    {
        "prompt": "Which kind of formula shows the actual number of each type of atom in a molecule?",
        "options": ["Empirical formula", "Molecular formula", "Structural formula only", "Net ionic formula"],
        "correct_option_index": 1,
        "explanation": "A molecular formula gives the actual numbers of each atom in a molecule.",
    },
    {
        "prompt": "What is the oxidation number of chlorine in NaCl?",
        "options": ["-1", "0", "+1", "+7"],
        "correct_option_index": 0,
        "explanation": "Chlorine is -1 in sodium chloride.",
    },
    {
        "prompt": "Which law explains why mass is neither created nor destroyed in a reaction?",
        "options": ["Law of multiple proportions", "Law of conservation of mass", "Law of definite proportions", "Ideal gas law"],
        "correct_option_index": 1,
        "explanation": "The law of conservation of mass says mass is conserved in chemical reactions.",
    },
    {
        "prompt": "Which bond angle is closest to the ideal angle in a tetrahedral molecule?",
        "options": ["90 degrees", "109.5 degrees", "120 degrees", "180 degrees"],
        "correct_option_index": 1,
        "explanation": "A perfect tetrahedral arrangement has bond angles of about 109.5 degrees.",
    },
    {
        "prompt": "What is the formula for potassium nitrate?",
        "options": ["KNO2", "KNO3", "K2NO3", "KNO4"],
        "correct_option_index": 1,
        "explanation": "Potassium nitrate is made of K+ and NO3-, giving KNO3.",
    },
    {
        "prompt": "Which substance is most likely to have hydrogen bonding between its molecules?",
        "options": ["CH4", "CO2", "NH3", "HCl"],
        "correct_option_index": 2,
        "explanation": "NH3 can form hydrogen bonds because hydrogen is bonded to nitrogen.",
    },
    {
        "prompt": "What is the oxidation number of elemental oxygen, O2?",
        "options": ["-2", "-1", "0", "+2"],
        "correct_option_index": 2,
        "explanation": "An element in its standard elemental form has an oxidation number of 0.",
    },
    {
        "prompt": "Which unit is commonly used for solution concentration in introductory chemistry?",
        "options": ["Molarity", "Newton", "Candela", "Volt"],
        "correct_option_index": 0,
        "explanation": "Molarity is one of the most common concentration units in introductory chemistry.",
    },
]
